Add tasks documentation
CompanyMood/api-documentation pull request #4
Opened 2018-11-24 14:19 UTC by th1988

2018-11-26 14:08 UTC, SweeD requested changes
Looks good to me, but one field is wrong. 
Thanks, good work! 👍

2018-11-26 14:08 UTC, SweeD commented on source/includes/_tasks.md
> +         "progress": '100%',
There is no DB attribute named `progress`
We have the field `percent` which is an integer.

2018-11-26 16:14 UTC, th1988 commented
Hey @SweeD,
changed it 👍

2018-11-27 10:23 UTC, SweeD approved these changes

2018-11-27 10:23 UTC, SweeD commented
Looks good to me. 👍 

Plese go ahead and 🚢 at your will. 🎉

2018-12-07 09:33 UTC, merged

2018-12-07 09:34 UTC, th1988 commented
@SweeD would you please deploy the changes? Or if you tell me how, I can do it by myself :)

2018-12-07 11:19 UTC, SweeD commented
Just use the `.deploy`script.